# =================================================================
# List of starting keys to crawl, by level. Format is key: name,
# where key is the eflora key# used on ucjeps.berkeley.edu, and
# name is the taxonomic-level identifier.
# =================================================================

crawler_start_url: "https://ucjeps.berkeley.edu/IJM_keys/toc.html"

family_keys:
  - "Salicaceae"
  - "Ericaceae"
  - "Rhamnaceae"
  - "Fagaceae"


genus_keys:
  - "Salix"