# =================================================================
# Application Config goes here
# =================================================================

defaults: &defaults
    # Database settings
    SQLALCHEMY_TRACK_MODIFICATIONS: false
    SQLALCHEMY_ENGINE_OPTIONS:
        pool_pre_ping: true

development:
    # Database settings
    DB_URI_PREFIX: "sqlite:///"
    DB_NAME: "app.db"
    <<: *defaults

testing:
    <<: *defaults

deployment:
    <<: *defaults
